# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'hederablog'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'about',   url: 'about.html'}
- {name: 'archive', url: 'writing.html'}
- {name: 'contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'youtube',    link: 'https://www.youtube.com/@jagmeemees'}
- {icon: 'github',     link: 'https://github.com/konomu'}
# - {icon: 'twitter',    link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin',   link: 'http://www.linkedin.com/in/lenpaul/'}
# - {icon: 'envelope',   link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: ''

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
